// This file is auto-generated by good_perf.py
    #include <math.h>
    //#pragma GCC optimize("Ofast")
    //#pragma GCC target("sse4")
    #pragma once
    const int MAX_LOG_N = 19;
    const int MAX_LOG_Q = 19;
    const int MAX_N = 1 << MAX_LOG_N;
    const int MAX_Q = 1 << MAX_LOG_Q;
    const int SQRT = pow(MAX_N, 0.69);
